// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PasswordManager.Data;

#nullable disable

namespace PasswordManager.Data.Migrations
{
    [DbContext(typeof(PwmDbContext))]
    [Migration("20250821061803_AddedVaultNameColumn")]
    partial class AddedVaultNameColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("PasswordManager.Data.Entities.VaultEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("EncryptedVaultKey")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("KdfIterations")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KdfMemoryKb")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KdfParallelism")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("KdfSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("VaultName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Vaults");
                });

            modelBuilder.Entity("PasswordManager.Data.Entities.VaultItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("NotesBlob")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordBlob")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UsernameBlob")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VaultId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
